name: SAM Build and Deploy

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: cd kjell/hello_world/ && pip install -r requirements.txt

      - name: SAM Build
        run: |
          cd kjell/
          sam build

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        if: github.ref == 'refs/heads/main'
        run: sam deploy --no-fail-on-empty-changeset